<div id="admin-user-index-grid"></div>

<script>
    $(document).ready(function () {
        var serviceUrl = "/admin/user/",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: serviceUrl + "read",
                    update: serviceUrl + "save",
                    destroy: serviceUrl + "delete",
                    create: serviceUrl + "save"
                },
                pageSize: <?=\Zend\Paginator\Paginator::getDefaultItemCountPerPage()?>,
                schema: {
                    model: {
                        id: "user_id",
                        fields: {
                            user_id: {type: "number", editable: false, nullable: true },
                            account: {validation: { required: true} },
                            real_name: { validation: { required: true} },
                            email: { validation: {required: true} },
                            status: { defaultValue: 0},
                            password: {editable: true}
                        }
                    },
                    "data": "data",
                    "total": "total"
                },
                error: function (e){
                    console.log("err", e);
                    if (e.status == "customerror") {
                        for (var i in e.errors) {
                            for (var j in e.errors[i]) {
                                alert(e.errors[i][j]);
                                break;
                            }
                            break;
                        }

                        $('#admin-user-index-grid').data("kendoGrid").cancelChanges();
                    }
                },
                serverPaging: true
            });

        var statusData = [{name: '开启', value:'0'},{name: '禁用', value:'1'}];
        $("#admin-user-index-grid").kendoGrid({
            dataSource: dataSource,
            pageable: true,
            toolbar: ["create"],
            columns:[
                { field: "account", title: "用户名", width: "100px"  },
                { field: "real_name", title:"真实姓名", width: "120px" },
                { field: "email", title:"Email", width: "200px", editor: emailEditor },
                { field: "status", title: "状态", editor: statusEditor, width: "100px", template: function (item){
                    return statusData[item.status].name;
                }},
                { field: "password", title: "密码", template: ''},
                { command: ["edit", "destroy",
                    {
                        name:"用户角色分配",
                        click: function (e){
                            var tr = $(e.target).closest("tr");
                            var data = this.dataItem(tr);
                            Platform.newWindow({
                                title: data.account + '::用户角色分配::用户管理',
                                content: '/admin/user/assign/id/'+data.user_id
                            });
                        }
                    }
                ], title: "&nbsp;" }
            ],
            editable: "inline",
            sortable: true,
            edit: function(e) {
                if (!e.model.isNew()) {
                    e.container.find("input[name=account]").attr('disabled', true);
                }
            }

//            cancel: function (e) { console.log('cancel', arguments); },
//            change: function (e) { console.log('change', arguments); },
//            columnHide: function (e) { console.log('columnHide', arguments); },
//            columnMenuInit: function (e) { console.log('columnMenuInit', arguments); },
//            columnReorder: function (e) { console.log('columnReorder', arguments); },
//            columnResize: function (e) { console.log('columnResize', arguments); },
//            columnShow: function (e) { console.log('columnShow', arguments); },
//            dataBinding: function (e) { console.log('dataBinding', arguments); },
//            dataBound: function (e) { console.log('dataBound', arguments); },
//            detailCollapse: function (e) { console.log('detailCollapse', arguments); },
//            detailExpand: function (e) { console.log('detailExpand', arguments); },
//            detailInit: function (e) { console.log('detailInit', arguments); },
//            edit: function (e) { console.log('edit', arguments); },
//            filterMenuInit: function (e) { console.log('filterMenuInit', arguments); },
//            remove: function (e) { console.log('remove', arguments); },
//            save: function (e) { console.log('save', arguments); },
//            saveChanges: function (e) { console.log('saveChanges', arguments); },
        });

        function emailEditor(container, options){
            $('<input required class="k-textbox k-invalid" name="' + options.field +
                '" data-bind="value:' + options.field + '" type="email" />')
                .appendTo(container);
        }

        function statusEditor(container, options) {
            $('<input required data-bind="value:' + options.field + '"/>')
                .appendTo(container)
                .kendoDropDownList({
                    dataTextField: "name",
                    dataValueField: "value",
                    dataSource: statusData
                });
        }
    });
</script>