<div class="system-permission-index-grid"></div>

<script>
    $(document).ready(function () {
        var crudServiceBaseUrl = "/system/permission/",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: crudServiceBaseUrl + "read",
                    update: crudServiceBaseUrl + "save"
                },
                group: [{ field: "module" }, { field: "controller" }],
                schema: {
                    model: {
                        id: "per_id",
                        fields: {
                            per_id: {type: "number", editable: false, nullable: true },
                            module: {editable: false},
                            controller: {editable: false},
                            action: {editable: false},
                            title: {validation: { required: true}}
                        }
                    }
                },
                error: function (e){
                    if (e.status == "customerror") {
                        for (var i in e.errors) {
                            for (var j in e.errors[i]) {
                                alert(e.errors[i][j]);
                                break;
                            }
                            break;
                        }

                        $('.system-permission-index-grid').data("kendoGrid").cancelChanges();
                    }
                }
            });

        $(".system-permission-index-grid").kendoGrid({
            dataSource: dataSource,
            pageable: false,
            groupable: true,
            editable: true,
            toolbar: [
                "save", "cancel",
                {
                    name: "system-permission-init",
                    text: '权限更新',
                    iconClass: 'k-icon',
                    imageClass: 'k-i-refresh',
                    attr: 'title="更新成功"'
                }
            ],
            columns:[
                { field: "per_id", title: "权限ID", width: "150px"},
                { field: "title", title: "权限名", width: "150px"},
                { field: "module", title: "模块", width: "150px"},
                { field: "controller", title: "控制器", width: "150px"},
                { field: "action", title: "动作", width: "150px"},
                { command: [
                    {
                        name:"分配角色权限",
                        click: function (e){
                            var tr = $(e.target).closest("tr");
                            var data = this.dataItem(tr);
                            Platform.newWindow({
                                title: data.title + '::权限分配',
                                content: '/system/permission/assign/id/'+data.per_id
                            });
                        }
                    }
                ], title: "&nbsp;"}
            ]
        });

        Platform.toolbarClick('system-permission-init', crudServiceBaseUrl + 'init');
    });
</script>