<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>账号登录 - 巨人移动管理平台</title>

    <!-- Bootstrap core CSS -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="js/jquery.min.js"></script>
    <!--<script src="bootstrap/js/bootstrap.min.js"></script>-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
            font-family: "微软雅黑";
        }

        #welcome {
            margin: 0 auto;
            float: none;
        }
    </style>

    <script>
        $.ajaxSetup({type: "POST", dataType: "json", error: function () {
            console.error('数据格式错误');
        }});
        $(function () {
            $('#login').submit(function () {
                $.post(location.href, $(this).serialize(), function (result) {
                    if (result.code == 1) {
                        location.href = '/admin';
                    } else {
                    }
                });
                return false;
            });
        });
    </script>
</head>

<body>

<div class="container">
    <div class="col-md-4" id="welcome">
    <form class="" role="form" id="login">
        <h2 class="form-signin-heading">账号登录: </h2>
        <div class="input-group input-group-lg">
            <span class="input-group-addon glyphicon glyphicon-user"></span>
            <input type="text" class="form-control" name="account" placeholder="请输入账号">
        </div>
        <br />
        <div class="input-group input-group-lg">
            <span class="input-group-addon glyphicon glyphicon-lock"></span>
            <input type="password" class="form-control" name="password" placeholder="请输入密码">
        </div>
        <br />
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    </form>
    </div>

</div> <!-- /container -->
</body>
</html>