<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Platform admin</title>
    <link href="./scripts/kendoui/styles/kendo.common.min.css" rel="stylesheet"/>
    <link href="./scripts/kendoui/styles/kendo.uniform.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="./styles/a/global.css"/>

    <script src="./scripts/jquery/jquery/jquery-2.1.1.min.js"></script>
    <script src="./scripts/kendoui/js/kendo.web.min.js"></script>
    <script src="./scripts/platform-admin/platform.js"></script>
</head>
<body>
<div>
    <div class="k-header" id="g-top">
        Zf Admin
    </div>
</div>
<div id="horizontal">
    <div id="left-pane">
    </div>
    <div id="main">
        <H1>Hello world!</H1>
    </div>
</div>
</body>

<script>
    $(document).ready(function() {
        $("body").kendoSplitter({
            orientation: "vertical",
            panes: [
                { collapsible: false, resizable: false, size: "60px"},
                { collapsible: false, resizable: false }
            ]
        });

        $("#horizontal").kendoSplitter({
            panes: [
                { collapsible: true, resizable: false, size: "220px", collapsedSize: "50px" },
                { collapsible: false }
            ]
        });

        $("#left-pane").kendoPanelBar({
            dataSource: [
                {
                    text: "Baseball",
                    items: [
                        { text: "Top News" },
                        { text: "Photo Galleries" },
                        { text: "Videos Records" },
                        { text: "Radio Records" }
                    ]
                },
                {
                    text: "Golf",
                    items: [
                        { text: "Top News" },
                        { text: "Photo Galleries" },
                        { text: "Videos Records" },
                        { text: "Radio Records" }
                    ]
                },
                {
                    text: "Swimming",
                    items: [
                        { text: "Top News" },
                        { text: "Photo Galleries" }
                    ]
                },
                {
                    text: "Snowboarding",
                    items: [
                        { text: "Photo Galleries" },
                        { text: "Videos Records" }
                    ]
                }
            ]
        });
    });
</script>
</html>