<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Platform admin</title>
    <link href="./scripts/kendoui/styles/kendo.common.min.css" rel="stylesheet"/>
    <link href="./scripts/kendoui/styles/kendo.uniform.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="./styles/a/global.css"/>

    <script src="./scripts/jquery/jquery/jquery-2.1.1.min.js"></script>
    <script src="./scripts/kendoui/js/kendo.web.min.js"></script>
    <script src="./scripts/platform-admin/platform.js"></script>
<!--    <script src="http://code.angularjs.org/angular-1.0.1.min.js"></script>-->
</head>
<body>
<div>
    <div class="k-header" id="g-top">

    </div>
</div>
<div id="horizontal" style="overflow: hidden">
    <div id="left-pane">
    </div>
    <div>
    <div id="main">
        <H1>Welcome!</H1>
    </div>
    </div>
</div>
</body>

<script>
    $(document).ready(function() {
        $.ajaxSetup({type: "POST"/*, dataType: "json"*/});
        $("body").kendoSplitter({
            orientation: "vertical",
            panes: [
                { collapsible: false, resizable: false, size: "60px"},
                { collapsible: false, resizable: false }
            ]
        });

        $("#horizontal").kendoSplitter({
            panes: [
                { collapsible: true, resizable: false, size: "220px", },
                { collapsible: false }
            ]
        });

        $.get('./admin/index/init', function (r) {
            $("#left-pane").kendoPanelBar({
                dataSource: r.menu,
                select: function (e) {
                    e.preventDefault();
                    var $item = $(e.item);
                    $('#main').load($item.find('a').attr('href'));
                }
            });
        });
    });
</script>
</html>