<?php echo $this->doctype(); ?>

<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Platform admin')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Bootstrap core CSS -->
    <link href="./scripts/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <script src="./scripts/jquery/jquery/jquery-2.1.1.min.js"></script>
    <!--<script src="bootstrap/js/bootstrap.min.js"></script>-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<div class="container">
    <?php echo $this->content; ?>
    <hr>
</div>
<!-- /container -->
<?php echo $this->inlineScript() ?>
</body>
</html>
