<form class="admin-role-assign-product-grid<?= $role_id ?>"></form>

<script>
    $(document).ready(function () {
        var serviceUrl = "./product/config/";
        var permissions = <?=json_encode($products)?>;
        var dataSource = new kendo.data.DataSource({
            transport: {
                read: serviceUrl + "read-for-permission"
            },
            pageSize: 20,
            schema: {
                model: {
                    id: "id",
                    fields: {
                        id: {type: "number", editable: false, nullable: true },
                        alias: { validation: { required: true} },
                        name: { validation: { required: true} },
                        status: { defaultValue: 0}
                    }
                },
                "data": "data",
                "total": "total"
            },
            serverFiltering: true,
            serverPaging: true
        });

        var $grid = $(".admin-role-assign-product-grid<?=$role_id?>");
        var $selectAll = $("<input type='checkbox'>").click(function () {
            $grid.find('input:checkbox[name="product_id[]"]').prop('checked', this.checked);
        });
        var statusData = [
            {name: '禁用', value: '0'},
            {name: '开启', value: '1'},
            {name: '待测', value: '2'}
        ];

        $grid.kendoGrid({
            dataSource: dataSource,
            pageable: true,
            toolbar: function () {
                var grid = $grid.data('kendoGrid');
                var $button = $(grid._createButton({
                    text: "确认分配",
                    name: "admin-role-assign-product",
                    imageClass: "k-i-tick",
                    iconClass: "k-icon"
                }));

                Platform.ui.toolbarClick($button, function () {
                    return {
                        url: '<?=$this->uri()->getPath()?>',
                        data: $grid.serialize(),
                        message: '分配成功'
                    };
                });
                return $button;
            },
            columns: [
                { field: "id", sortable: false, title: "&nbsp;", template: '<input type="checkbox" name="product_id[]" value="#=id#">', width: 40},
                { field: "id", title: "产品编码", width: "100px"  },
                { field: "name", title: "名称", width: "120px" },
                { field: "alias", title: "别名", width: "120px" },
                {
                    field: "status",
                    title: "状态",
                    template: function (item) {
                        return statusData[item.status].name;
                    }
                }
            ],
            sortable: true,
            dataBound: function (e) {
                $.each(permissions, function (i, id) {
                    $grid.find('input:checkbox[value=' + id + ']').prop('checked', true);
                });
            }
        }).data('kendoGrid').thead.find('th:first').append($selectAll);
    });
</script>