<div>
    <div id="admin-role-toolbar"></div>
    <br>

    <div id="admin-role-tree"></div>
</div>
<div class="admin-trees-index-tree-add-form pa-box">
    <form class="form">
        <ul>
            <li>
                <label>上级菜单:</label>
                <span class="parent-name"></span>
            </li>
            <li>
                <label for="role_name">角色名称:</label>
                <input type="text" class="k-textbox" name="role_name" autofocus="autofocus" required/>
            </li>
            <li>
                <input type="hidden" class="k-textbox" name="role_id"/>
            </li>
            <li>
                <input type="hidden" class="k-textbox" name="parent_id"/>
            </li>
            <li class="form-row">
                <button class="k-button" id="add_submit"><span class="k-icon k-i-tick"></span>提 交</button>
                <button type="button" class="closeButton">返回</button>
            </li>
        </ul>
    </form>
</div>

<div class="admin-trees-index-tree-edit-form pa-box">
    <form class="form">
        <ul>
            <li>
                <label for="role_name">角色名称:</label>
                <input type="text" class="k-textbox" name="role_name" autofocus="autofocus" required/>
            </li>
            <li>
                <input type="hidden" class="k-textbox" name="role_id"/>
            </li>
            <li>
                <input type="hidden" class="k-textbox" name="parent_id"/>
            </li>
            <li class="form-row">
                <button class="k-button" id="edit_submit"><span class="k-icon k-i-tick"></span>提 交
                </button>
                <button type="button" class="closeButton">返回</button>
            </li>
        </ul>
    </form>
</div>
<style>
    #admin-trees-index-tree {
        float: left;
    }

    .admin-trees-index-tree-add-form,
    .admin-trees-index-tree-edit-form {
        padding: 2em;
        width: 460px;
        display: none;
    }

    .admin-trees-index-tree-add:hover,
    .admin-trees-index-tree-delete:hover {
        opacity: 0.5;
    }
</style>

<script>
    $(function () {
        var $toolbar = $("#admin-role-toolbar").kendoToolBar({
            items: [
                {
                    type: "button",
                    text: "增加ROOT角色",

                    click: function () {
                        alert(1);
                    },
                    icon: "plus"
                },
                {
                    type: "button",
                    id: "role-assign-permission",
                    text: "分配角色权限",
                    enable: false,
                    click: function () {
                        alert(1);
                    }
                },
                {
                    type: "button",
                    id: "role-assign-user",
                    text: "用户角色分配",
                    enable: false,
                    click: function () {
                        alert(1);
                    }
                }
            ]
        });
        a = $toolbar;
        $.get('./admin/role/read', function (data) {
            var $tree = $("#admin-role-tree").kendoTreeView({
                    dragAndDrop: true,
                    dataSource: data.roles,
                    checkboxes: true,
                    template: kendo.template($("#admin-trees-index-tree-template").html()),
                    select: function (e) {
                        $toolbar.data("kendoToolBar").enable('#role-assign-permission');
                        $toolbar.data("kendoToolBar").enable('#role-assign-user');
                        var dataItem = $treeView.dataItem(e.node);
                    },
                    drop: function (e) {
                        console.log(e);
                        if (e.dropPosition != 'over') {
                            e.setValid(false);
                        }
                        if (!e.destinationNode || !e.valid) {
                            e.setValid(false);
                            return;
                        }

                        var sourceNode = $treeView.dataItem(e.sourceNode),
                            destinationNode = $treeView.dataItem(e.destinationNode);

                        var $targetNode = $(e.destinationNode), allow = false;
                        $targetNode.parents('.k-item').andSelf().each(function () {
                            var parentItem = $treeView.dataItem(this);
                            if ($.inArray(parseInt(parentItem.role_id), data.access_roles) > -1) {
                                allow = true;
                            }
                        });
                        e.setValid(allow);
                    },
                    dragend: function (e) {
                        var sourceNode = $treeView.dataItem(e.sourceNode),
                            destinationNode = $treeView.dataItem(e.destinationNode),
                            data = {"role_id": sourceNode.role_id, "name": sourceNode.text, "parent": destinationNode.role_id};

                        if (e.dropPosition == 'over') {
                            $.post('./admin/role/update', data, function (e) {
                                sourceNode.set('parent_id', destinationNode.role_id);
                            });
                        }
                    }
                }),
                $treeView = $tree.data('kendoTreeView');

//                $treeView.select($());
            $treeView.expand(".k-item");


            //节点添加
            $tree.on("click", ".admin-role-add", function (e) {
                e.preventDefault();

                var $item = $(this).closest(".k-item"),
                    dataItem = $treeView.dataItem($item),
                    roleName = prompt("请输入角色名");

                if (roleName) {
                    $.post('./admin/role/add', {'name': roleName, parent: dataItem.role_id}, function (result) {
                        $treeView.append({
                            "text": result.name,
                            "role_id": result.role_id,
                            "parent_id": dataItem.role_id
                        }, $item);
                    });
                }
            });

            //节点删除
            $tree.on("click", ".admin-role-delete", function (e) {
                e.preventDefault();

                if (confirm('确认删除?')) {

                    var node = $(this).closest(".k-item"),
                        dataItem = $treeView.dataItem(node),
                        nodes = node.find('.k-item').andSelf(),
                        data = [];

                    nodes.each(function () {
                        var nodeData = $treeView.dataItem(this);
                        data.push(nodeData.role_id);

                    });

                    $.post('./admin/role/delete', {'roles': data}, function () {
                        $treeView.remove(node);
                    });
                }
            });

            //节点名称编辑
            $tree.on("dblclick", "span.k-in", function (e) {
                e.preventDefault();

                var $item = $(this).closest(".k-item"),
                    dataItem = $treeView.dataItem($item),
                    roleName = prompt("请输入角色名", dataItem.text);

                if (roleName) {
                    $.post(
                        './admin/role/update',
                        {'name': roleName, role_id: dataItem.role_id, parent: dataItem.parent_id},
                        function (result) {
                            $item.find('span.k-text').html(roleName);
                        }
                    );
                }

                return false;
            });

        });
        /*

         */
        /*
         //添加菜单

         //编辑菜单

         $treeView.select($());
         $treeView.expand(".k-item");

         //Root节点添加
         $('#admin-trees-index-tree-add').click(function () {

         $addform.parent().fadeIn(200).siblings('.pa-box').hide();
         $addform.find('input:role_name').val('');
         $addform.find('span.parent-name').html('根菜单');
         $addform.find('input:first').focus();
         return false;
         });

         $(".closeButton").kendoButton({
         icon: "cancel"
         }).on('click', function (e) {
         $addform.parent().fadeOut(200);
         $editForm.parent().fadeOut(200);
         });
         //节点添加
         $tree.on("click", ".admin-trees-index-tree-add", function (e) {

         var dataItem = $treeView.dataItem($(this).closest(".k-item"));

         $addform.parent().fadeIn(200).siblings('.pa-box').hide();

         $addform.find('input:text').val('');
         $addform.find('span.parent-name').html(dataItem.text);
         $addform.find('input[name=role_id]').val(dataItem.role_id);
         $addform.find('input[name=parent]').val(dataItem.parent);
         $addform.data('appendParent', $(this).closest(".k-item"));
         $addform.find('input:first').focus();

         return false;
         });

         //节点删除
         $tree.on("click", ".admin-trees-index-tree-delete", function (e) {

         e.preventDefault();

         var node = $(this).closest(".k-item"),
         dataItem = $treeView.dataItem(node),
         nodes = node.find('.k-item').andSelf(),
         data = new Array();

         nodes.each(function () {
         var nodeData = $treeView.dataItem(this);
         data.push(nodeData.role_id);

         });

         $.post('./admin/role/delete', {'data': data}, function () {
         $treeView.remove(node);
         });

         return false;
         });

         $('#add_submit').paRemoteClick(function (e) {

         e.preventDefault();

         var parent = $addform.data('appendParent') || undefined,
         data = {"name": $addform.get(0).role_name.value, "parent": $addform.get(0).role_id.value};

         return {
         url: './admin/role/save',
         data: data,
         success: function (result) {
         if (result.errors) {
         alert(result.errors);
         } else {
         result = {"text": $addform.get(0).role_name.value, "role_id": result.role_id, "parent_id": result.parent};
         $treeView.append(result, parent);
         $addform.parent().fadeOut(200);
         }
         }
         };
         });

         $('#edit_submit').paRemoteClick(function (e) {

         e.preventDefault();

         var current = $editForm.data('current') || undefined,
         data = {"role_id": $editForm.get(0).role_id.value, "name": $editForm.get(0).role_name.value, "parent": $editForm.get(0).parent_id.value};

         return {
         url: './admin/role/save',
         data: data,
         success: function (result) {

         if (result.errors) {
         alert(result.errors);
         } else {

         var item = $treeView.dataItem(current);
         item.set('role_name', result.name);
         item.set('role_id', result.role_id);
         item.set('parent_id', result.parent);
         $treeView.text($editForm.data('current'), result.name);

         $editForm.parent().fadeOut(200);
         }
         }
         };
         });*/
    });

</script>

<script id="admin-trees-index-tree-template" type="text/kendo-ui-template">
    <span class="k-text">#: item.text #</span>
    <span class="admin-role-add k-icon k-i-plus"></span>
    <span class="admin-role-delete k-icon k-i-close"></span>
</script>