<div id="admin-role-index-grid"></div>

<script>
    $(document).ready(function () {
        var serviceUrl = "./admin/role/",
            dataSource = new kendo.data.TreeListDataSource({
                transport: {
                    read: serviceUrl + "read",
                    update: serviceUrl + "save",
                    destroy: serviceUrl + "delete",
                    create: serviceUrl + "save"
                },
                schema: {
                    model: {
                        id: "role_id",
                        fields: {
                            role_id: {type: "number", editable: false, nullable: true},
                            name: {validation: {required: true}},
                            parentId: {validation: {required: true}}
                        }
                    },
//                    parse: function(response) {
//                        for (var i=0; i < response.data.length; i++) {
//                            response.data[i].parentId = response.data[i].parent == '0' ? null : response.data[i].parent;
//                            response.data[i].parent = response.data[i].parent == '0' ? null : response.data[i].parent;
//                        }
//                        console.log( response.data);
//                        return response;
//                    },
                    "data": "data",
                    "total": "total"
                },
                error: function (e) {
                }
            });
        $("#admin-role-index-grid").kendoTreeList({
            dataSource: dataSource,
            height: 540,
            columns: [
                {field: "Name"},
                {field: "Phone"}
            ]
        });
    });
</script>