<div class="admin-user-assign-toolbar"></div>
<form class="admin-user-assign-view">
</form>
<script>
    $(document).ready(function () {
        var roles = <?=json_encode($roles)?>;
        var dataSource = new kendo.data.DataSource({
            transport: {
                read: "./admin/role/read"
            },
            schema: {
                model: {
                    id: "role_id",
                    fields: {
                        role_id: {type: "number", editable: false, nullable: true},
                        name: {validation: {required: true}}
                    }
                }
            }
        });

        var $tree = $(".admin-user-assign-view");

        var $selectAll = $("<input type='checkbox'>").click(function () {
            $tree.find('input:checkbox[name="role_id[]"]').prop('checked', this.checked);
        });

        $.get('./admin/role/read', function (data) {
            $tree.kendoTreeView({
                dragAndDrop: true,
                dataSource: data.roles,
                checkboxes: {
                    template: "<input type='checkbox' name='role_id[]' value='#=item.role_id#' />"
                }
            });
            var $treeView = $tree.data('kendoTreeView');
            $treeView.select($()); // clears selection
            $treeView.expand(".k-item,.k-top");

            $.each(roles, function (i, id) {
                $tree.find('input:checkbox[value='+id+']').prop('checked', this.checked);
            });
        });

        $('.admin-user-assign-toolbar').kendoToolBar({
            items: [
                {
                    type: "button",
                    text: "确认分配",
                    click: function () {
                        $.post(
                            './admin/user/assign/id/<?=$user_id?>',
                            $tree.serialize(),
                            function () {
                                alert('更新成功');
                            }
                        );
                    }
                }
            ]
        });
    });
</script>