<div id="admin-user-index-grid"></div>

<script>
    $(document).ready(function () {
        var serviceUrl = "./admin/user/",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: serviceUrl + "read",
                    update: serviceUrl + "save",
                    destroy: serviceUrl + "delete",
                    create: serviceUrl + "save"
                },
                schema: {
                    model: {
                        id: "user_id",
                        fields: {
                            user_id: {type: "number", editable: false, nullable: true},
                            account: {validation: {required: true}},
                            real_name: {validation: {required: true}},
                            email: {validation: {required: true}},
                            status: {defaultValue: 0},
                            password: {editable: true}
                        }
                    },
                    "data": "data",
                    "total": "total"
                },
                error: function (e) {
                    if (e.status == "customerror") {
                        for (var i in e.errors) {
                            for (var j in e.errors[i]) {
                                alert(e.errors[i][j]);
                                break;
                            }
                            break;
                        }

                        $('#admin-user-index-grid').data("kendoGrid").cancelChanges();
                    }
                },
                pageSize: 15,
                serverFiltering: true,
                serverPaging: true,
                serverSorting: false
            }),
            statusData = [
                {text: '开启', value: '0'},
                {text: '禁用', value: '1'}
            ],
            $grid = $("#admin-user-index-grid");

        $grid.kendoGrid({
            dataSource: dataSource,
            pageable: true,
            toolbar: [
                {'name': 'create', 'text': '增加'},
                {
                    name: "admin-assign-role",
                    text: '用户角色分配'
                }
            ],
            filterable: {
                extra: false,
                messages: {
                    info: "查找: ",
                    filter: "提交",
                    clear: "清除",
                    selectValue: "------选择------",
                    and: "并且",
                    or: "或者"
                },
                operators: {
                    string: {
                        contains: "模糊查找"
                    },
                    number: {
                        eq: "等于"
                    },
                    date: {
                        ge: "大于等于",
                        le: "小于",
                        gt: "大于",
                        lt: "小于"
                    },
                    enums: {
                        eq: "满足条件"
                    }
                }
            },
            columns: [
                {field: "account", title: "用户名", width: "100px"},
                {field: "real_name", title: "真实姓名", width: "120px"},
                {field: "email", title: "Email", width: "200px", editor: emailEditor},
                {field: "status", type: "enums", title: "状态", values: statusData, width: "100px"},
                {field: "password", title: "密码", template: '', hidden: true},
                {
                    command: [
                        {'name': 'edit', 'text': '编辑'},
                        {'name': 'destroy', 'text': '删除'}
                    ], title: "&nbsp;", width: 260
                }
            ],
            selectable: true,
            editable: "popup",
            sortable: true,
            edit: function (e) {
                if (!e.model.isNew()) {
                    e.container.find("input[name=account]").prop('disabled', true);
                }
            }
        }),
        kGrid = $grid.data('kendoGrid');

        function emailEditor(container, options) {
            $('<input required class="k-textbox k-invalid" name="' + options.field +
            '" data-bind="value:' + options.field + '" type="email" />')
                .appendTo(container);
        }

        function statusEditor(container, options) {
            $('<input required data-bind="value:' + options.field + '"/>')
                .appendTo(container)
                .kendoDropDownList({
                    dataTextField: "name",
                    dataValueField: "value",
                    dataSource: statusData
                });
        }

        $grid.on('click', '.k-grid-admin-assign-role', function () {
            $('<div>').appendTo('body').kendoWindow({
                width: "70%",
                height: '70%',
                title: '用户角色分配',
                content: "./admin/user/assign/id/" + kGrid.dataItem(kGrid.select()).id,
                close: function () {
                    this.destroy();
                },
                modal: true
            }).data('kendoWindow').center();
        });
    });
</script>