<form class="admin-role-assign-grid"></form>
<script>
    $(document).ready(function () {
        var permissions = <?=json_encode($permissions)?>;
        var dataSource = new kendo.data.DataSource({
                transport: {
                    read: "/admin/permission/read"
                },
                group: [{ field: "module" }, { field: "controller" }],
                schema: {
                    model: {
                        id: "per_id",
                        fields: {
                            per_id: {type: "number", editable: false, nullable: true },
                            module: {editable: false},
                            controller: {editable: false},
                            action: {editable: false},
                            title: {validation: { required: true}}
                        }
                    }
                }
            });

        var $grid = $(".admin-role-assign-grid");

        var $selectAll = $("<input type='checkbox'>").click(function (){
            $grid.find('input:checkbox[name="per_id[]"]').prop('checked', this.checked);
        });

        $grid.kendoGrid({
            dataSource: dataSource,
            pageable: false,
//            groupable: true,
            toolbar: function () {
                var grid = $grid.data('kendoGrid');
                var $button = $(grid._createButton({
                    text:"确认分配",
                    name:"admin-role-assign",
                    imageClass:"k-i-tick",
                    iconClass:"k-icon"
                }));

                Platform.toolbarClick($button, function (){
                    return {
                        url: '<?=$this->uri()->getPath()?>',
                        data: $grid.serialize(),
                        message: '分配成功'
                    };
                });

                var $collapseAll = $(grid._createButton({
                    text:"收缩",
                    name:"collapse",
                    imageClass:"k-i-collapse",
                    iconClass:"k-icon"
                })).click(function (){
                    $grid.find('.k-i-collapse').click();
                });

                var $expandAll = $(grid._createButton({
                    text:"展开",
                    name:"expand",
                    imageClass:"k-i-expand",
                    iconClass:"k-icon"
                })).click(function (){
                        $grid.find('.k-i-expand').click();
                    });

                return $('<div />').append($button).append($expandAll).append($collapseAll);
            },
            columns:[
                { field: "per_id", title: "&nbsp;", template:'<input type="checkbox" name="per_id[]" value="#=per_id#">', width: 40},
                { field: "title", title: "权限名", width: "150px"},
                { field: "module", hidden: true, title: "模块"},
                { field: "controller", hidden: true, title: "控制器"},
                { field: "action", title: "动作"}
            ],
            dataBound: function(e) {
                $.each(permissions, function (i, id){
                    $grid.find('input:checkbox[value='+id+']').prop('checked', true);
                });
            }
        }).data('kendoGrid').thead.find('th:first').append($selectAll);
    });
</script>