<form class="admin-role-assign-user-grid"></form>

<script>
    $(document).ready(function () {
        var permissions = <?=json_encode($users)?>;
        var dataSource = new kendo.data.DataSource({
                transport: {
                    read: "/admin/user/read"
                },
                pageSize: 20,
                schema: {
                    model: {
                        id: "user_id",
                        fields: {
                            user_id: {type: "number", editable: false, nullable: true },
                            account: {validation: { required: true} },
                            real_name: { validation: { required: true} },
                            status: { defaultValue: 0}
                        }
                    },
                    "data": "data",
                    "total": "total"
                }
            });

        var $grid = $(".admin-role-assign-user-grid");
        var $selectAll = $("<input type='checkbox'>").click(function (){
            $grid.find('input:checkbox[name="user_id[]"]').prop('checked', this.checked);
        });
        var statusData = [{name: '开启', value:'0'}, {name: '禁用', value:'1'}];

        $grid.kendoGrid({
            dataSource: dataSource,
            pageable: true,
            toolbar: function (){
                var grid = $grid.data('kendoGrid');
                var $button = $(grid._createButton({
                    text:"确认分配",
                    name:"admin-role-assign-user",
                    imageClass:"k-i-tick",
                    iconClass:"k-icon"
                }));

                Platform.toolbarClick($button, function (){
                    return {
                        url: '<?=$this->uri()->getPath()?>',
                        data: $grid.serialize(),
                        message: '分配成功'
                    };
                });
                return $button;
            },
            columns:[
                { field: "user_id", sortable:false, title: "&nbsp;", template:'<input type="checkbox" name="user_id[]" value="#=user_id#">', width: 40},
                { field: "account", title: "用户名", width: "100px"  },
                { field: "real_name", title:"真实姓名", width: "120px" },
                {
                    field: "status",
                    title: "状态",
                    template: function (item){
                        return statusData[item.status].name;
                    }
                }
            ],
            sortable: true,
            dataBound: function(e) {
                $.each(permissions, function (i, id){
                    $grid.find('input:checkbox[value='+id+']').prop('checked', true);
                });
            }
        }).data('kendoGrid').thead.find('th:first').append($selectAll);
    });
</script>