<div id="ui-config-list">

</div>
<script>
    $(function () {
        var serviceUrl = "./model-manager/ui-config/",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: serviceUrl + "read",
                    update: serviceUrl + "save",
                    destroy: serviceUrl + "delete",
                    create: serviceUrl + "save"
                },
                schema: {
                    model: {
                        id: "id",
                        fields: {
                            id: {type: "number", editable: false, nullable: true },
                            source: {editable: false, nullable: true },
                            name: { validation: { required: true} }
                        }
                    },
                    "data": "data",
                    "total": "total"
                },
                error: function (e) {
                    if (e.status == "customerror") {
                        for (var i in e.errors) {
                            for (var j in e.errors[i]) {
                                alert(e.errors[i][j]);
                                break;
                            }
                            break;
                        }

                        $('#admin-user-index-grid').data("kendoGrid").cancelChanges();
                    }
                },
                pageSize: 15,
                serverFiltering: true,
                serverPaging: true,
                serverSorting: false
            });

        $("#ui-config-list").kendoGrid({
            dataSource: dataSource,
            pageable: true,
            filterable: {
                extra: false,
                messages: {
                    info: "查找: ",
                    filter: "提交",
                    clear: "清除",
                    selectValue: "------选择------",
                    and: "并且",
                    or: "或者"
                },
                operators: {
                    string: {
                        contains: "模糊查找"
                    },
                    number: {
                        eq: "等于"
                    },
                    date: {
                        ge: "大于等于",
                        le: "小于",
                        gt: "大于",
                        lt: "小于"
                    },
                    enums: {
                        eq: "满足条件"
                    }
                }
            },
            columns: [
                { field: "name",  title: "名称", width: "150px"  },
                { field: "source", title: "数据源", width: "200px" },
                { template:'<a href="./model-manager/source/view/id/#:id#" target="_blank">./model-manager/source/view/id/#:id#</a>', title: "查看链接"  },
                { command: [
                    {'name': 'edit', 'text': '编辑'},
                    {'name': 'destroy', 'text': '删除'}
                ], title: "&nbsp;", width: "200px" }
            ],
            selectable: true,
            sortable: true
        });

    });
</script>