<div class="admin-permission-index-grid"></div>

<script>
    $(document).ready(function () {
        var $grid = $('.admin-permission-index-grid'),
            serviceUrl = "/admin/permission/",
            dataSource = new kendo.data.DataSource({
                transport: {
                    read: serviceUrl + "read",
                    update: serviceUrl + "save"
                },
                group: [{ field: "module" }, { field: "controller" }],
                schema: {
                    model: {
                        id: "per_id",
                        fields: {
                            per_id: {type: "number", editable: false, nullable: true },
                            module: {editable: false},
                            controller: {editable: false},
                            action: {editable: false},
                            title: {validation: { required: true}}
                        }
                    }
                },
                error: function (e){
                    if (e.status == "customerror") {
                        for (var i in e.errors) {
                            for (var j in e.errors[i]) {
                                alert(e.errors[i][j]);
                                break;
                            }
                            break;
                        }

                        $grid.data("kendoGrid").cancelChanges();
                    }
                }
            });

        $grid.kendoGrid({
            dataSource: dataSource,
            pageable: false,
            groupable: true,
            editable: true,
            toolbar: [
                "save", "cancel",
                {
                    name: "admin-permission-init",
                    text: '权限更新',
                    iconClass: 'k-icon',
                    imageClass: 'k-i-refresh',
                    attr: 'title="更新成功"'
                }
            ],
            columns:[
                { field: "per_id", title: "权限ID", width: "150px"},
                { field: "title", title: "权限名", width: "150px"},
                { field: "module", title: "模块", width: "150px"},
                { field: "controller", title: "控制器", width: "150px"},
                { field: "action", title: "动作", width: "150px"},
                { command: [
                    {
                        name:"分配角色权限",
                        click: function (e){
                            var tr = $(e.target).closest("tr");
                            var data = this.dataItem(tr);
                            Platform.newWindow({
                                title: data.title + '::权限分配',
                                content: '/admin/permission/assign/id/'+data.per_id
                            });
                        }
                    }
                ], title: "&nbsp;"}
            ],
            dataBound: function(e) {
                $grid.closest('.k-window-content').data('kendoWindow').center();
            }
        });

        Platform.toolbarClick('admin-permission-init', serviceUrl + 'init');
    });
</script>