<div class="col-md-4" id="welcome">
    <form class="" role="form" id="login">
        <h2 class="form-signin-heading">账号登录: </h2>

        <div class="input-group input-group-lg">
            <span class="input-group-addon glyphicon glyphicon-user"></span>
            <input type="text" class="form-control" name="account" placeholder="请输入账号">
        </div>
        <br/>

        <div class="input-group input-group-lg">
            <span class="input-group-addon glyphicon glyphicon-lock"></span>
            <input type="password" class="form-control" name="password" placeholder="请输入密码">
        </div>
        <br/>
        <button class="btn btn-lg btn-primary btn-block" type="submit">登录</button>
    </form>
</div>