<div class="admin-permission-assign-toolbar"></div>
<form class="admin-permission-assign-grid"></form>
<script>
    $(document).ready(function () {
        var roles = <?=json_encode($roles)?>;

        var $tree = $(".admin-permission-assign-grid");

        $.get('./admin/role/read', function (data) {
            $tree.kendoTreeView({
                dragAndDrop: true,
                dataSource: data.roles,
                checkboxes: {
                    template: "<input type='checkbox' name='role_id[]' value='#=item.role_id#' />"
                }
            });
            var $treeView = $tree.data('kendoTreeView');
            $treeView.select($()); // clears selection
            $treeView.expand(".k-item");

            $.each(roles, function (i, id) {
                $tree.find('input:checkbox[value='+id+']').prop('checked', true);
            });
        });

        $('.admin-permission-assign-toolbar').kendoToolBar({
            items: [
                {
                    type: "button",
                    text: "全选/反选",
                    click: function (e) {
                        var checked = $(e.target).data('checked');
                        $tree.find('input:checkbox[name="role_id[]"]').prop('checked', !checked);
                        $(e.target).data('checked', !checked);
                    }
                },
                {
                    type: "button",
                    text: "确认分配",
                    click: function () {
                        $.post(
                            '<?=$this->uri()->getPath()?>',
                            $tree.serialize(),
                            function () {
                                alert('更新成功');
                            }
                        );
                    }
                }
            ]
        });
    });
</script>