<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Admin framework</title>
    <link href="/kendoui/styles/kendo.common.min.css" rel="stylesheet"/>
    <link href="/kendoui/styles/kendo.default.min.css" rel="stylesheet"/>
    <link rel="stylesheet" href="/styles/global.css"/>
    <script src="/js/jquery.min.js"></script>
    <script src="/js/platform.js"></script>
    <script src="/kendoui/js/kendo.web.min.js"></script>
    <!--[if lte IE 8]>
    <script src="https://github.com/douglascrockford/JSON-js/blob/master/json2.js"></script><![endif]-->

    <script>
        $.ajaxSetup({type: "POST", dataType: "json"});
        $(document).ready(function () {
            $("#menu").kendoMenu({
                select: function (e) {
                    var $item = $(e.item);
                    console.log($item, 'open:' + $item.data('url'));

                    if ($item.data('platformWindow')) {
                        $item.data('platformWindow').data("kendoWindow").open();
                    } else if ($item.data('url')) {
                        var $win = Platform.newWindow({
                            title: $item.text(),
                            content: $item.data('url'),
                            close: function () {
                                this.destroy();
                                $item.removeData('platformWindow');
                            }
                        });
                        $item.data('platformWindow', $win);
                    }
                }
            });
        });
    </script>
    <style>
        #window {
            margin-top: 1em;
        }
        .p-block {
            width: 150px;
        }
    </style>
</head>
<body>
<div id="page">
    <ul id="menu">
        <li>
            系统
            <ul>
                <li data-url="/admin/user">
                    用户管理
                </li>
                <li data-url="/admin/role">
                    角色管理
                </li>
                <li data-url="/admin/permission">
                    权限管理
                </li>
                <li data-url="/admin/index/self">
                    个人信息
                </li>
            </ul>
        </li>
        <li>
            积分商城
            <ul>
                <li data-url="/shop/goods">
                    商品管理
                </li>
                <li data-url="/shop/category">
                    商品类别管理
                </li>
                <li data-url="/shop/game-category">
                    商品游戏分类
                </li>
                <li data-url="/shop/order">
                    订单管理
                </li>
                <li data-url="/shop/express">
                    快递地区管理
                </li>
            </ul>
        </li>
    </ul>
    <div id="window">
        <div class="p-block k-block k-shadow">Block with shadow</div>
    </div>
</div>
<div class="tasks"></div>
</body>
</html>